### ISSUE TITLE
Handle version differences with URL parameter fields

### ISSUE THREAD

**Issue by look** [github/elastomer-client#178]
Certain document hash keys are "special" and get converted into URL parameters rather than being indexed with the document.

These fields are added to a document. They get pulled out and added to the query
string (rather than being passed in a a parameter to the index method). Any unknown underscore fields are ignored and indexed as usual.

https://github.com/github/elastomer-client/blob/9e96707e74ab890607f5cd795cf186a9af457898/lib/elastomer/client/docs.rb#L520

These URL parameters are different between versions. `_consistency` got re-implemented as `_wait_for_active_shards` and has different values, so it's not a direct mapping. 

Additionally, ES 5 no longer allows unknown URL parameters. So we need to not send it or force the caller to deal with the error. And vice-versa, there is a problem as well: if someone uses a new
parameter from ES 5, it will end up in a document as a field unless we pull it out and put it on the URL as a parameter (which ES 2 will ignore), or pull it out and ignore it.

We need to decide how to handle these differences in the library.

References:

* [ES 5 `wait_for_active_shards`](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/docs-index_.html#index-wait-for-active-shards)
* [ES 2 `consistency`](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/docs-index_.html#index-consistency)
* [Issue about the change](https://github.com/elastic/elasticsearch/issues/21804)

**Comment by look** [comment]
Here's my proposal:

1. Have one list of `SPECIAL_KEYS` for each version of ES that we support:

```
COMMON_SPECIAL_KEYS = ["foo", "bar"]
ES_2_X_SPECIAL_KEYS = ["consistency"]
ES_5_X_SPECIAL_KEYS = ["wait_for_active_shards"]

def special_keys
  if es_version_2_x?
    COMMON_SPECIAL_KEYS + ES_2_X_SPECIAL_KEYS
  else
    ...
  end
end
```

2. Any special key for the current version of ES gets converted into a URL parameter like now.
3. Any special key that is a known parameter for a _different_ version of ES causes an error (for example, attempting to use `_wait_for_active_shards` against ES 2 would raise an error in our library).
4. Any other underscore key that is not flagged as a special key for any version of Elasticsearch will be indexed as a field as they are today.

**Comment by TwP** [comment]
The other option here is to retain only the `SPECIAL_KEYS` that are common to both ES 2.X and ES 5.X with the intention of removing `SPECIAL_KEYS` completely in the future. We can make a note of which keys are removed so that we can find and handle those cases over in the main application.

The approach you specified above will also work very nicely. It has the advantage of retaining the most compatibility. But we will still need to check our own application for these use cases (`_consistency` and `_wait_for_active_shards`) and handle them appropriately.

**Comment by look** [comment]
That would definitely work, too. And I would prefer to not pass these as fields of the document (I think it's clearer that they are parameters). Either way, we will need to audit the code for incompatible keys. With my approach things will fail fast rather than getting indexed which is what will happen with your approach.

Side note: a few more of the special fields have been removed from ES 5 and will need to be dealt with: `_timestamp` and `_ttl`. They do not have direct replacements.

**Comment by elireisman** [comment]
Again, I'm still getting a feel for the codebase here so take w/grain of salt but so far I like @look's approach with versioned lists and failing fast when the wrong params are present rather than indexing them by surprise. None of the options strike me as bad though, so I'd be fine with any of these at this juncture.

**Comment by TwP** [comment]
I'm all for the fail fast approach then. So let's implement that and keep track of list of special keys to audit for when this gem release goes live.

**Comment by look** [comment]
👍 I'm on it
